- name: Set timezone to {{ samba_timezone }}
  community.general.timezone:
    name: "{{ samba_timezone }}"

- name: Set fact for first samba domain controller
  ansible.builtin.set_fact:
    first_samba_dc_name_fact: "{{ groups[samba_dc_inventory_group][0] }}"

- name: Gather ip address of {{ first_samba_dc_name_fact }}
  ansible.builtin.setup:
    filter:
      - all_ipv4_addresses
  register: first_samba_dc_facts
  delegate_to: "{{ first_samba_dc_name_fact }}"

- name: Set fact for samba domain controller ip address
  ansible.builtin.set_fact:
    samba_dc_ip_fact: "{{ first_samba_dc_facts['ansible_facts']['ansible_all_ipv4_addresses'][0] }}"

- name: Output hostinfo
  ansible.builtin.debug:
    msg: |
      Hostname: {{ ansible_hostname }}
      DC-IPv4: {{ samba_dc_ip_fact }}
      Domain: {{ samba_domainname }}

- name: Set hostname to ansible_hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"

- name: Edit hostname in hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "127.0.1.1\t{{ ansible_hostname }}"
    state: present
    line: "{{ ansible_facts.all_ipv4_addresses[0] }}\t{{ ansible_hostname }}.{{ samba_domainname }} {{ ansible_hostname }}"
    backup: true

- name: Copy ntp.conf
  ansible.builtin.copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    backup: true
    force: true
    mode: '644'
